#include <fbjni/fbjni.h>

#include "KilneGitNativeOnLoad.hpp"  // generated by Nitrogen

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, []() {
    margelo::nitro::kilne::git::registerAllNatives();
  });
}
