#pragma once

#include "HybridGitSpec.hpp"  // generated by Nitrogen from Git.nitro.ts

#include <atomic>
#include <memory>
#include <string>
#include <vector>

namespace margelo::nitro::kilne::git {

/**
 * HybridObject that wraps libgit2.
 *
 * All public methods run on a libgit2 worker thread (Nitro schedules Promise
 * bodies on a background queue) — they never block the JS thread.
 *
 * libgit2 is initialised lazily on first use and reference-counted via the
 * constructor / destructor pair. The native instance is a singleton cached
 * in JS (`getGit()` in `src/index.ts`).
 */
class HybridGit : public HybridGitSpec {
public:
  HybridGit();
  ~HybridGit() override;

  // HybridObject
  std::string getExternalMemorySize() noexcept override {
    // No significant external allocations outside the ones libgit2 tracks itself.
    return "N/A";
  }

  // Property
  std::string getVersion() override;

  // Sync / async ops
  std::shared_ptr<Promise<std::string>> init(const std::string& localPath) override;

  std::shared_ptr<Promise<CloneResult>> clone(
      const std::string& url,
      const std::string& localPath,
      const std::optional<GitCredentials>& credentials,
      const std::optional<CloneOptions>& options) override;

  std::shared_ptr<Promise<PullResult>> pull(
      const std::string& localPath,
      const std::optional<GitCredentials>& credentials,
      const std::optional<InsecureOptions>& options) override;

  std::shared_ptr<Promise<CommitAndPushResult>> commitAllAndPush(
      const std::string& localPath,
      const std::string& message,
      const std::optional<GitCredentials>& credentials,
      const std::optional<CommitAndInsecureOptions>& options) override;

  std::shared_ptr<Promise<PushResult>> push(
      const std::string& localPath,
      const std::optional<GitCredentials>& credentials,
      const std::optional<InsecureOptions>& options) override;

  std::shared_ptr<Promise<StatusResult>> status(const std::string& localPath) override;

  std::shared_ptr<Promise<bool>> isRepository(const std::string& localPath) override;

private:
  // libgit2 global state is refcounted; track our init count so we don't
  // accidentally shut it down while another instance still uses it.
  std::atomic<bool> _initialised{false};
};

}  // namespace margelo::nitro::kilne::git
