#pragma once

#include "HybridGitSpec.hpp"  // generated by Nitrogen from Git.nitro.ts

#include <memory>
#include <string>

namespace margelo::nitro::kilne::git {

/**
 * HybridObject that wraps libgit2.
 *
 * All public methods run on a Nitro background queue — they never block the JS
 * thread. Concurrent calls that touch the same `localPath` are serialized with
 * a per-path mutex so libgit2 repository handles are not used concurrently.
 *
 * libgit2 is initialised once per process via `std::call_once`. The native
 * instance is a singleton cached in JS (`getGit()` in `src/index.ts`).
 */
class HybridGit : public HybridGitSpec {
public:
  HybridGit();
  ~HybridGit() override;

  // HybridObject
  size_t getExternalMemorySize() noexcept override {
    // No significant external allocations outside the ones libgit2 tracks itself.
    return 0;
  }

  // Property
  std::string getVersion() override;

  // Sync / async ops
  std::shared_ptr<Promise<CloneResult>> clone(
      const std::string& url,
      const std::string& localPath,
      const std::optional<GitCredentials>& credentials,
      const std::optional<CloneOptions>& options) override;

  std::shared_ptr<Promise<PullResult>> pull(
      const std::string& localPath,
      const std::optional<GitCredentials>& credentials) override;

  std::shared_ptr<Promise<CommitAndPushResult>> commitAllAndPush(
      const std::string& localPath,
      const std::string& message,
      const std::optional<GitCredentials>& credentials,
      const std::optional<CommitOptions>& options) override;

  std::shared_ptr<Promise<PushResult>> push(
      const std::string& localPath,
      const std::optional<GitCredentials>& credentials) override;

  std::shared_ptr<Promise<StatusResult>> status(const std::string& localPath) override;

  std::shared_ptr<Promise<bool>> isRepository(const std::string& localPath) override;
};

}  // namespace margelo::nitro::kilne::git
